import { createHash } from "node:crypto";
import { availableParallelism, totalmem } from "node:os";
import {
  chromium,
  firefox,
  webkit,
  type Browser,
  type BrowserContext,
  type BrowserContextOptions,
  type Page,
} from "@playwright/test";
import type { TargetSource, SingleActorFlowSource } from "@polymux/protocol";

export type CrawlBrowserName = "chromium" | "firefox" | "webkit";

export interface WebCrawlOptions {
  url: string;
  browser?: CrawlBrowserName;
  maxPages?: number;
  maxDepth?: number;
  timeoutMs?: number;
  replays?: number;
  headers?: Record<string, string>;
  storageState?: BrowserContextOptions["storageState"];
}

export interface CrawlPageResult {
  requestedUrl: string;
  url: string;
  depth: number;
  status?: number;
  title?: string;
  links: string[];
  eligible: boolean;
  candidateEligible: boolean;
  reasons: string[];
  accessSignals: string[];
  observationHash?: string;
  flow?: SingleActorFlowSource;
  filename?: string;
}

export interface WebCrawlResult {
  formatVersion: 1;
  seedUrl: string;
  startedAt: string;
  finishedAt: string;
  durationMs: number;
  concurrency: number;
  maxConcurrent: number;
  maxPages: number;
  maxDepth: number;
  replays: number;
  visited: number;
  eligibleCandidates: number;
  accessWarnings: number;
  pages: CrawlPageResult[];
}

interface Assertion {
  target: TargetSource;
  key: string;
}

interface ProbeResult {
  url: string;
  status?: number;
  title?: string;
  links: string[];
  assertion?: Assertion;
  signature?: string;
  reasons: string[];
  accessSignals: string[];
}

interface FrontierItem {
  url: string;
  depth: number;
}

const browserTypes = { chromium, firefox, webkit } as const;
const unsafePath = /(?:^|[/_.-])(delete|destroy|logout|log-out|signout|sign-out|unsubscribe|remove)(?:$|[/_.-])/i;
const allowedMethods = new Set(["GET", "HEAD", "OPTIONS"]);

function positiveInteger(value: number, name: string): number {
  if (!Number.isInteger(value) || value < 1) {
    throw new RangeError(`${name} must be a positive integer`);
  }
  return value;
}

function nonNegativeInteger(value: number, name: string): number {
  if (!Number.isInteger(value) || value < 0) {
    throw new RangeError(`${name} must be a non-negative integer`);
  }
  return value;
}

function automaticCrawlConcurrency(): number {
  const cpuCapacity = Math.max(1, Math.floor(availableParallelism() / 2));
  const memoryCapacity = Math.max(
    1,
    Math.floor((totalmem() / 1024 ** 3 - 2) / 0.5),
  );
  return Math.max(1, Math.min(8, cpuCapacity, memoryCapacity));
}

async function mapConcurrent<T, R>(
  items: readonly T[],
  concurrency: number,
  worker: (item: T, index: number) => Promise<R>,
): Promise<R[]> {
  const results = new Array<R>(items.length);
  let next = 0;
  async function consume(): Promise<void> {
    while (next < items.length) {
      const index = next++;
      results[index] = await worker(items[index] as T, index);
    }
  }
  await Promise.all(
    Array.from({ length: Math.min(concurrency, items.length) }, consume),
  );
  return results;
}

function canonicalUrl(value: string, origin: string): string | undefined {
  let url: URL;
  try {
    url = new URL(value, origin);
  } catch {
    return undefined;
  }
  if (url.origin !== origin || !["http:", "https:"].includes(url.protocol)) {
    return undefined;
  }
  if (unsafePath.test(url.pathname)) return undefined;
  url.hash = "";
  url.searchParams.sort();
  return url.toString();
}

function relativeUrl(value: string, origin: string): string {
  const url = new URL(value);
  return `${url.pathname}${url.search}` || "/";
}

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 52);
}

function flowFilename(url: string, title: string | undefined): string {
  const digest = createHash("sha256").update(url).digest("hex").slice(0, 8);
  const path = new URL(url).pathname.split("/").filter(Boolean).at(-1);
  return `${slug(path || title || "home") || "page"}-${digest}.flow.yaml`;
}

function flowFor(
  probe: ProbeResult,
  seedOrigin: string,
  timeoutMs: number,
): SingleActorFlowSource | undefined {
  if (!probe.assertion) return undefined;
  const location = relativeUrl(probe.url, seedOrigin);
  const label = probe.title?.trim() || location;
  return {
    version: 1,
    name: `Crawl: ${label}`,
    description: `Generated by polymux crawl from ${location}.`,
    tags: [],
    platforms: ["web"],
    baseUrl: seedOrigin,
    timeoutMs,
    setup: [],
    steps: [
      { launch: { app: "web", clearState: true } },
      { navigate: location },
      { expect: { target: probe.assertion.target, state: "visible" } },
    ],
    teardown: [],
  };
}

async function prepareContext(
  browser: Browser,
  seedOrigin: string,
  mutationAttempts: string[],
  options: Pick<WebCrawlOptions, "headers" | "storageState">,
): Promise<BrowserContext> {
  const context = await browser.newContext({
    ...(options.headers ? { extraHTTPHeaders: options.headers } : {}),
    ...(options.storageState ? { storageState: options.storageState } : {}),
  });
  await context.route("**/*", async (route) => {
    const request = route.request();
    if (!allowedMethods.has(request.method())) {
      mutationAttempts.push(`${request.method()} ${request.url()}`);
      await route.abort("blockedbyclient");
      return;
    }
    let requestOrigin: string | undefined;
    try {
      requestOrigin = new URL(request.url()).origin;
    } catch {
      requestOrigin = undefined;
    }
    if (request.isNavigationRequest() && requestOrigin !== seedOrigin) {
      await route.abort("blockedbyclient");
      return;
    }
    await route.continue();
  });
  return context;
}

async function inspectPage(
  page: Page,
  url: string,
  origin: string,
  timeoutMs: number,
): Promise<Omit<ProbeResult, "reasons">> {
  const response = await page.goto(url, {
    waitUntil: "domcontentloaded",
    timeout: timeoutMs,
  });
  await page.locator("body").waitFor({ state: "visible", timeout: timeoutMs });
  const status = response?.status();
  const snapshot = await page.evaluate(() => {
    const visible = (element: Element): boolean => {
      const style = getComputedStyle(element);
      const rectangle = element.getBoundingClientRect();
      return style.visibility !== "hidden" && style.display !== "none" && rectangle.width > 0 && rectangle.height > 0;
    };
    const text = (element: Element): string =>
      (element.textContent ?? "").replace(/\s+/g, " ").trim();
    return {
      title: document.title.trim(),
      headings: Array.from(document.querySelectorAll("h1,h2,h3,h4,h5,h6"))
        .filter(visible)
        .map(text)
        .filter(Boolean),
      mainCount: Array.from(document.querySelectorAll("main,[role=main]"))
        .filter(visible).length,
      passwordInputs: Array.from(document.querySelectorAll('input[type="password"]'))
        .filter(visible).length,
      links: Array.from(document.querySelectorAll("a[href]"))
        .filter(visible)
        .filter((element) => !element.hasAttribute("download"))
        .map((element) => (element as HTMLAnchorElement).href),
    };
  });
  const headingCounts = new Map<string, number>();
  for (const heading of snapshot.headings) {
    headingCounts.set(heading, (headingCounts.get(heading) ?? 0) + 1);
  }
  const uniqueHeading = snapshot.headings.find(
    (heading) => headingCounts.get(heading) === 1,
  );
  const assertion: Assertion | undefined = uniqueHeading
    ? {
        target: { role: "heading", name: uniqueHeading },
        key: `heading:${uniqueHeading}`,
      }
    : snapshot.mainCount === 1
      ? { target: { role: "main" }, key: "role:main" }
      : undefined;
  const links = [
    ...new Set(
      snapshot.links
        .map((link) => canonicalUrl(link, origin))
        .filter((link): link is string => link !== undefined),
    ),
  ].sort();
  const finalUrl = canonicalUrl(page.url(), origin) ?? url;
  const signature = assertion
    ? createHash("sha256")
        .update(JSON.stringify({
          finalUrl,
          title: snapshot.title,
          assertion,
          links,
          passwordInputs: snapshot.passwordInputs,
        }))
        .digest("hex")
    : undefined;
  return {
    url: finalUrl,
    ...(status !== undefined ? { status } : {}),
    ...(snapshot.title ? { title: snapshot.title } : {}),
    links,
    ...(assertion ? { assertion } : {}),
    ...(signature ? { signature } : {}),
    accessSignals: [
      ...(status === 401 ? ["http-401"] : []),
      ...(status === 403 ? ["http-403"] : []),
      ...(snapshot.passwordInputs > 0 ? ["visible-password-form"] : []),
    ],
  };
}

async function probe(
  browser: Browser,
  url: string,
  origin: string,
  timeoutMs: number,
  options: Pick<WebCrawlOptions, "headers" | "storageState">,
): Promise<ProbeResult> {
  const reasons: string[] = [];
  const mutations: string[] = [];
  const pageErrors: string[] = [];
  const failedRequests: string[] = [];
  const context = await prepareContext(browser, origin, mutations, options);
  const page = await context.newPage();
  page.on("pageerror", (error) => pageErrors.push(error.message));
  page.on("requestfailed", (request) => {
    if (mutations.some((entry) => entry.endsWith(request.url()))) return;
    try {
      const requestUrl = new URL(request.url());
      if (requestUrl.origin === origin && ["document", "script", "xhr", "fetch"].includes(request.resourceType())) {
        failedRequests.push(`${request.resourceType()} ${request.url()}`);
      }
    } catch {
      // Ignore malformed third-party request URLs.
    }
  });
  try {
    const result = await inspectPage(page, url, origin, timeoutMs);
    const requested = new URL(url);
    const final = new URL(result.url);
    const redirectedToAuthentication =
      requested.pathname !== final.pathname &&
      /(?:^|[/_.-])(auth|login|log-in|signin|sign-in)(?:$|[/_.-])/i.test(final.pathname);
    if (redirectedToAuthentication) {
      result.accessSignals.push(`authentication-redirect:${requested.pathname}->${final.pathname}`);
      reasons.push("authentication-required");
    }
    if (result.status === undefined || result.status < 200 || result.status >= 400) {
      reasons.push(`document-status:${result.status ?? "none"}`);
    }
    if (!result.assertion) reasons.push("no-unique-semantic-anchor");
    if (mutations.length > 0) reasons.push("mutation-attempted");
    if (pageErrors.length > 0) reasons.push("page-error");
    if (failedRequests.length > 0) reasons.push("same-origin-request-failed");
    return { ...result, reasons };
  } catch (error) {
    reasons.push(`probe-failed:${error instanceof Error ? error.message : String(error)}`);
    return { url, links: [], reasons, accessSignals: [] };
  } finally {
    await context.close();
  }
}

export async function crawlWebApp(options: WebCrawlOptions): Promise<WebCrawlResult> {
  const started = new Date();
  const seed = new URL(options.url);
  if (!["http:", "https:"].includes(seed.protocol)) {
    throw new Error("Crawl URL must use http or https");
  }
  seed.hash = "";
  seed.searchParams.sort();
  const maxPages = positiveInteger(options.maxPages ?? 50, "maxPages");
  const maxDepth = nonNegativeInteger(options.maxDepth ?? 4, "maxDepth");
  const timeoutMs = positiveInteger(options.timeoutMs ?? 10_000, "timeoutMs");
  const replays = positiveInteger(options.replays ?? 3, "replays");
  const concurrency = automaticCrawlConcurrency();
  const browser = await browserTypes[options.browser ?? "chromium"].launch({ headless: true });
  const seen = new Set<string>([seed.toString()]);
  const discovered: Array<{ item: FrontierItem; probe: ProbeResult }> = [];
  let frontier: FrontierItem[] = [{ url: seed.toString(), depth: 0 }];
  let active = 0;
  let maxConcurrent = 0;
  const runProbe = async (url: string): Promise<ProbeResult> => {
    active += 1;
    maxConcurrent = Math.max(maxConcurrent, active);
    try {
      return await probe(browser, url, seed.origin, timeoutMs, {
        ...(options.headers ? { headers: options.headers } : {}),
        ...(options.storageState ? { storageState: options.storageState } : {}),
      });
    } finally {
      active -= 1;
    }
  };
  try {
    while (frontier.length > 0 && discovered.length < maxPages) {
      const remaining = maxPages - discovered.length;
      const layer = frontier.sort((a, b) => a.url.localeCompare(b.url)).slice(0, remaining);
      const probes = await mapConcurrent(layer, concurrency, ({ url }) => runProbe(url));
      for (let index = 0; index < layer.length; index += 1) {
        discovered.push({ item: layer[index]!, probe: probes[index]! });
      }
      const nextDepth = (layer[0]?.depth ?? maxDepth) + 1;
      if (nextDepth > maxDepth) break;
      const children = probes.flatMap((result) => result.links).sort();
      const next: FrontierItem[] = [];
      for (const child of children) {
        if (seen.has(child)) continue;
        seen.add(child);
        next.push({ url: child, depth: nextDepth });
      }
      frontier = next;
    }

    const validationWork = discovered.flatMap(({ probe: initial }, pageIndex) =>
      initial.reasons.length === 0 && initial.signature
        ? Array.from({ length: Math.max(0, replays - 1) }, (_, replayIndex) => ({
            pageIndex,
            replayIndex,
            url: initial.url,
          }))
        : [],
    );
    const validations = await mapConcurrent(
      validationWork,
      concurrency,
      ({ url }) => runProbe(url),
    );
    const validationByPage = new Map<number, ProbeResult[]>();
    for (let index = 0; index < validationWork.length; index += 1) {
      const work = validationWork[index]!;
      const entries = validationByPage.get(work.pageIndex) ?? [];
      entries.push(validations[index]!);
      validationByPage.set(work.pageIndex, entries);
    }

    const pages = discovered.map(({ item, probe: initial }, pageIndex): CrawlPageResult => {
      const reasons = [...initial.reasons];
      const validation = validationByPage.get(pageIndex) ?? [];
      if (
        reasons.length === 0 &&
        validation.some((entry) => entry.reasons.length > 0 || entry.signature !== initial.signature)
      ) {
        reasons.push("replay-mismatch");
      }
      const eligible = reasons.length === 0;
      const flow = eligible ? flowFor(initial, seed.origin, timeoutMs) : undefined;
      const candidateEligible = flow !== undefined;
      return {
        requestedUrl: item.url,
        url: initial.url,
        depth: item.depth,
        ...(initial.status !== undefined ? { status: initial.status } : {}),
        ...(initial.title ? { title: initial.title } : {}),
        links: initial.links,
        eligible,
        candidateEligible,
        reasons,
        accessSignals: initial.accessSignals,
        ...(initial.signature ? { observationHash: initial.signature } : {}),
        ...(flow ? { flow, filename: flowFilename(initial.url, initial.title) } : {}),
      };
    });
    const finished = new Date();
    return {
      formatVersion: 1,
      seedUrl: seed.toString(),
      startedAt: started.toISOString(),
      finishedAt: finished.toISOString(),
      durationMs: finished.getTime() - started.getTime(),
      concurrency,
      maxConcurrent,
      maxPages,
      maxDepth,
      replays,
      visited: pages.length,
      eligibleCandidates: pages.filter((page) => page.candidateEligible).length,
      accessWarnings: pages.filter((page) => page.accessSignals.length > 0).length,
      pages,
    };
  } finally {
    await browser.close();
  }
}
